[server]
headless = true
address = "0.0.0.0"
port = 8501
maxUploadSize = 1024

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#f0b90b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f5f7"
textColor = "#1f2933"
